---
title: "Genomic prediction for fatty acids"
author: "Malachy Campbell"
date: "12/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "/Users/malachycampbell/Documents/Dropbox/Work/Oats/DivPanel_Met_HH/statTargetQC/flashr")
```

## Genomic prediction for fatty acids
```{r, echo = T, eval = F}
library(BGLR)
library(argparse)

rm(list = ls())

parser <- ArgumentParser(description = "Does GWAS for many metabolites/traits")
parser$add_argument("--arrayNo", dest="arrayNo", required=TRUE, help="Uses the array number to subset for fold")
args <- parser$parse_args()

JobNo <- as.numeric(args$arrayNo) #index for each method/trait/fold

InputDP <- readRDS("../InputData_FAs.rds")
InputElite <- readRDS("../InputData_FAs_elite.rds")

lookupTable <- data.frame(Method = rep(c("BRR", "BL", "BayesA", "BayesB", "BayesC"), each = 45),
                          Trait = rep(c(rep("C16.0", 5),
                                        rep("C18.1", 5),
                                        rep("C18.2", 5),
                                        rep("C18.0", 5),
                                        rep("C18.3", 5),
                                        rep("C14.0", 5),
                                        rep("C20.0", 5),
                                        rep("C20.1", 5),
                                        rep("C16.1", 5)), 5),
                          Fold = rep(c(1:5), 45))

## Submit only first 90 for testing
tmpMeth <- lookupTable$Method[JobNo]
tmpTrt <- lookupTable$Trait[JobNo]
tmpFold <- lookupTable$Fold[JobNo]
##

perChange <- function(NoCols = NULL, data = NULL){
  return(((data[,1:(NoCols/2)] - data[,((NoCols/2) + 1):(NoCols)]) / data[,((NoCols/2) + 1):(NoCols)]) * 100)
}

# Subset and order markers
commonMrks <- intersect(InputElite$mapData$marker, InputDP$map$marker)
length(commonMrks) #54152
mrkEff <- InputElite$mrkEff[[tmpTrt]]; mrkEff <- mrkEff[row.names(mrkEff) %in% commonMrks ,]
dim(mrkEff)
mrks <- InputElite$mrks; mrks <- mrks[, colnames(mrks) %in% commonMrks]
mrkEff <- mrkEff[match(colnames(mrks), row.names(mrkEff)) ,]

# mrks <- mrks[order(row.names(mrks)) ,] #order markers by line name
phenos <- InputElite$phenotypes
#phenos$line <- droplevels(phenos$line)
phenos <- phenos[order(phenos$env, phenos$line) ,]

Ys <- scale(phenos[c(3:ncol(phenos))], center = T, scale = T)

Zsc <- scale(mrks, center = T, scale = T)
row.names(Zsc) <- InputElite$mrks$V1
###########################
# Create the gBLUP kernel #
###########################
G_gBLUP <- tcrossprod(Zsc)/ncol(mrks)
G_gBLUP <- G_gBLUP + diag(nrow(G_gBLUP))*0.0001

# Incidence matrices for lines and trials
Zg <- model.matrix(~line-1, data = phenos)
Ze <- model.matrix(~env-1, data = phenos)
Zg <- Zg[, match(paste0("line", colnames(G_gBLUP)), colnames(Zg))]

sum(colnames(Zg) == paste0("line", colnames(G_gBLUP)))

ETA_gBLUP <- list()
G_gBLUP <- Zg %*% G_gBLUP %*% t(Zg)
ETA_gBLUP[[1]] <- list(K = G_gBLUP, model = "RKHS")
envKernel <- Ze %*% t(Ze)
ETA_gBLUP[[2]] <- list(K = envKernel, model = "RKHS")

##############################
# Create the informed kernel #
##############################
mrkEff <- (mrkEff[, which(tmpMeth == c("BRR", "BL", "BayesA", "BayesB", "BayesC"))]^2)/sum(mrkEff[, which(tmpMeth == c("BRR", "BL", "BayesA", "BayesB", "BayesC"))]^2)
G_info <- Zsc %*% diag(mrkEff) %*% t(Zsc)
G_info <- G_info + diag(nrow(G_info))*0.0001
ETA_info <- list()
G_info <- Zg %*% G_info %*% t(Zg)
ETA_info[[1]] <- list(K = G_info, model = "RKHS")
ETA_info[[2]] <- list(K = envKernel, model = "RKHS")

#Loop over the reps (columns of FldIndx). Select the appropriate fold 
corMat <- matrix(NA, ncol = 2, nrow = 50)
Ys <- Ys[, which(colnames(Ys) == tmpTrt), drop = F]
for(i in 1:50){
  trnLines <- row.names(InputElite$fldIndx)[which(InputElite$fldIndx[,i] != tmpFold)]
  Ytrn <- Ys
  Ytrn[! phenos$line %in% trnLines ,] <- NA
  
  ## Informed
  fm <- BGLR::BGLR(y = Ytrn[,1], ETA = ETA_info, nIter = 20000, burnIn = 5000, thin = 5)
  
  corMat[i, 1] <- cor(Ys[!phenos$line %in% trnLines, drop = F ,], 
                      (fm$ETA[[1]]$u[!phenos$line %in% trnLines]),
                      use = "complete.obs")
  
  ## gBLUP
  fm <- BGLR::BGLR(y = Ytrn[,1], ETA = ETA_gBLUP, nIter = 20000, burnIn = 5000, thin = 5)
  
  corMat[i, 2] <- cor(Ys[!phenos$line %in% trnLines, drop = F ,], 
                      (fm$ETA[[1]]$u[!phenos$line %in% trnLines]),
                      use = "complete.obs")
}

saveRDS(corMat, paste0("../FA/output/FA_", tmpTrt, "_", tmpMeth, "_", tmpFold, ".rds"))
```

## Compare TGRM-BLUP with gBLUP
```{r, echo = T, eval = F}
library(plyr)

rm(list = ls())

Meth <- c("BRR", "BL", "BayesA", "BayesB", "BayesC")
Trts <- c("C16.0", "C18.1", "C18.2", "C18.0", "C18.3", "C14.0", "C20.0", "C20.1", "C16.1")
flds <- 1:5

allRes <- NULL
for(m in Meth){
  for(ts in Trts){
    for(fld in flds){
      file <- paste0("../../../KernelPred_Front/FA/output/FA_", ts, "_", m, "_", fld, ".rds")
      if(file.exists(file)){
        tmp <- readRDS(file)
        fileName <- sub("../../../KernelPred_Front/FA/output/FA_", "", file)
        fileName <- sub(".rds", "", fileName)
        fileName <- as.vector(strsplit(fileName, "_", 3)[[1]])
        allRes <- rbind(allRes, data.frame(tmp, trt = fileName[1], 
                                           Method = fileName[2], 
                                           Fold = fileName[3],
                                           Rep = 1:50))
      }else{
        next
      }
    }
  }
}
colnames(allRes)[1:2] <- c("Info", "gBLUP")
allRes$PerDiff <- (allRes$Info - allRes$gBLUP)/allRes$gBLUP * 100

allRes <- ddply(allRes, .(trt, Method, Rep), summarise, Info = mean(Info), 
                gBLUP = mean(gBLUP, na.rm = T), PerDiff = mean(PerDiff, na.rm = T))

allRes_perDiff <- allRes[c(1:3, 6)]
allRes_perDiff$Imp <- ifelse(allRes$PerDiff > 0, 1, 0)
impFreq <- plyr::ddply(allRes_perDiff, .(trt, Method), summarise, Freq = mean(Imp))

xtable::xtable(reshape2::dcast(Method ~ trt, data = impFreq))


allRes_Cor <- allRes[c(1:4)]
allRes_Cor_g <- allRes[c(1,3,5)]
allRes_Cor_g <- plyr::ddply(allRes_Cor_g, .(trt, Rep), summarise, gBLUP = mean(gBLUP))
allRes_Cor <- rbind(allRes_Cor, 
                    data.frame(trt = allRes_Cor_g$trt, Method = "gBLUP", Rep = allRes_Cor_g$Rep, Info = allRes_Cor_g$gBLUP))

# allRes_Cor <- allRes_Cor[order(as.character(allRes_Cor$trt)) ,]

pdf("../../../KernelPred_Front/Manuscript/Figs/FA_PA.pdf", h = 6, w = 5.2)
nf = layout(rbind(c(1,1), c(2,2)))

###########
# Panel A #
###########
par(mar = c(4.5, 3.5, 1.5, 1.5), mgp=c(2.5,1,0), xpd = T)
boxplot(Info ~ Method*trt, las = 2, allRes_Cor, medlwd = 1.25,
        at = c(1,2,3,4,5,6, 9,10,11,12,13,14, 17,18,19,20,21,22, 
               25,26,27,28,29,30, 33,34,35,36,37,38, 41,42,43,44,45,46,
               49,50,51,52,53,54, 57,58,59,60,61,62, 65,66,67,68,69,70), 
        ylab = "r", col = c(wesanderson::wes_palette("Darjeeling1")[1], 
                            wesanderson::wes_palette("Darjeeling2")[1:4],
                            wesanderson::wes_palette("Darjeeling1")[2]), 
        xlab = "", cex = 0.5, xaxt = "n")

axis(1, at = c(3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5, 67.5), 
     labels = sub("\\.", ":", unique(allRes_Cor$trt)), las = 2, cex.axis = 0.7, font = 1)

legend("topleft", legend = c("Bayes A", "Bayes B", expression("Bayes C"*pi), "BL", "BRR", "gBLUP"), 
       fill = c(wesanderson::wes_palette("Darjeeling1")[1], 
                wesanderson::wes_palette("Darjeeling2")[1:4],
                wesanderson::wes_palette("Darjeeling1")[2]), bty = "n", cex = 0.65)

mtext("A", 2, adj=6, las=1, padj=-11, font=1, cex=0.8)
###########
# Panel B #
###########
par(mar = c(3.5, 3.5, 1.5, 1.5), mgp=c(2.5,1,0), xpd = T)
boxplot(PerDiff ~ Method*trt, las = 2, allRes_perDiff, medlwd = 1.25,
        at = c(1,2,3,4,5, 8,9,10,11,12, 15,16,17,18,19, 
               21,22,23,24,25, 28,29,30,31,32, 35,36,37,38,39,
               42,43,44,45,46, 49,50,51,52,53, 56,57,58,59,60), 
        ylab = "% diff.", col = c(wesanderson::wes_palette("Darjeeling1")[1], 
                                  wesanderson::wes_palette("Darjeeling2")[1:4]), 
                                  xlab = "", cex = 0.5, xaxt = "n")

axis(1, at = c(3, 10, 17, 23, 30, 37, 44, 51, 58), 
     labels = sub("\\.", ":", unique(allRes_Cor$trt)), las = 2, cex.axis = 0.7, font = 1)

legend("topright", legend = c("Bayes A", "Bayes B", expression("Bayes C"*pi), "BL", "BRR"), 
       fill = c(wesanderson::wes_palette("Darjeeling1")[1], 
                wesanderson::wes_palette("Darjeeling2")[1:4]), bty = "n", cex = 0.65)

mtext("B", 2, adj=6, las=1, padj=-11, font=1, cex=0.8)
dev.off()
```


% latex table generated in R 4.0.3 by xtable 1.8-4 package
% Fri Nov 20 10:36:16 2020
\begin{table}[ht]
\centering
\begin{tabular}{rlrrrrrrrrr}
  \hline
 & Method & C14.0 & C16.0 & C16.1 & C18.0 & C18.1 & C18.2 & C18.3 & C20.0 & C20.1 \\ 
  \hline
  BayesA & 0.82 & 1.00 & 0.80 & 1.00 & 0.38 & 0.98 & 0.28 & 1.00 & 0.54 \\ 
  BayesB & 1.00 & 1.00 & 0.96 & 1.00 & 0.54 & 1.00 & 0.58 & 1.00 & 0.92 \\ 
  BayesC & 1.00 & 1.00 & 0.96 & 1.00 & 0.58 & 0.98 & 0.62 & 1.00 & 0.86 \\ 
  BL & 0.74 & 1.00 & 0.94 & 1.00 & 0.52 & 0.98 & 0.50 & 1.00 & 0.74 \\ 
  BRR & 0.96 & 1.00 & 0.92 & 1.00 & 0.48 & 1.00 & 0.62 & 1.00 & 0.68 \\ 
   \hline
\end{tabular}
\end{table}

## Compare Bayesian Methods
```{r, echo = T, eval = F}
library(plyr)

rm(list = ls())

Meth <- c("BRR", "BL", "BayesA", "BayesB", "BayesC")
Trts <- c("C16.0", "C18.1", "C18.2", "C18.0", "C18.3", "C14.0", "C20.0", "C20.1", "C16.1")
flds <- 1:5

allRes <- NULL
for(m in Meth){
  for(ts in Trts){
    for(fld in flds){
      file <- paste0("../../../KernelPred_Front/FA/output/FA_", ts, "_", m, "_", fld, ".rds")
      if(file.exists(file)){
        tmp <- readRDS(file)
        fileName <- sub("../../../KernelPred_Front/FA/output/FA_", "", file)
        fileName <- sub(".rds", "", fileName)
        fileName <- as.vector(strsplit(fileName, "_", 3)[[1]])
        allRes <- rbind(allRes, data.frame(tmp, trt = fileName[1], 
                                           Method = fileName[2], 
                                           Fold = fileName[3],
                                           Rep = 1:50))
      }else{
        next
      }
    }
  }
}
colnames(allRes)[1:2] <- c("Info", "gBLUP")

allRes <- ddply(allRes, .(trt, Method, Rep), summarise, Info = mean(Info), 
                gBLUP = mean(gBLUP, na.rm = T))

allRes_Cor <- allRes[c(1:4)]

allRes_Cor <- reshape2::dcast(allRes_Cor, trt + Rep ~ Method, value.var = "Info")

perDiff_func <- function(data = NULL, BaseMeth = NULL, Method = NULL, Trait = NULL){
  tmpData <- data[data$trt %in% Trait ,]
  perDiff <- ((tmpData[c(Method)] - tmpData[c(BaseMeth)])/tmpData[c(BaseMeth)] )*100
  return(perDiff)
}

resList <- list()
Meths <- colnames(allRes_Cor)[3:7]
for(TRT in unique(allRes_Cor$trt)){ # Loop over traits
  resDF <- matrix(NA, ncol = 5, nrow = 5)
  colnames(resDF) <- row.names(resDF) <- Meths
  for(i in 1:(length(Meths))){ # loop over base method
   for(j in 1:length(Meths)){ # loop over all other methods
     BaseM <- Meths[i]
     intM <- Meths[j]
     tmpPD <- perDiff_func(data = allRes_Cor, BaseMeth = BaseM, Method = intM, Trait = TRT)
     resDF[i,j] <- apply(tmpPD, 2, function(x) sum(x > 0, na.rm = T)/length(x))
   } 
  }
  resList[[TRT]] <- resDF
}

resList <- do.call("rbind", resList)
resList <- data.frame(Trt = rep(unique(allRes_Cor$trt), each = 5), BaseMethod = row.names(resList), resList)
print(xtable::xtable(resList), include.rownames=FALSE)

colSums(
  do.call("rbind",lapply(resList, function(x) {
  apply(x, 2, function(y) ifelse(sum(y > 0.9), 1 ,0))
  })))

foo <- perDiff_func(data = allRes_Cor, 
                    BaseMeth = colnames(allRes_Cor)[3], 
                    Method = colnames(allRes_Cor)[4], 
                    Trait = unique(allRes_Cor$trt)[1])
```
